language: php

sudo: required

php:
  - 5.6

env:
  - TESTER_PHP_BIN="php-cgi"

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s -c ./tests/php.ini ./tests

before_script:
  - sudo apt-get install php5-json
  - phpenv config-add tests/php.ini
  - composer install
